version: '3.8'

services:
  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - microservices-network

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - microservices-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
